esphome:
  name: "rd6006-controller"
  comment: "Controls RD6006 PSU over MODBUS"
  name_add_mac_suffix: false
  project:
    name: "wildekek.rd6006-controller"
    version: "1.0.0"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG
  # Disable logging via UART, since we're using this for modbus communication
  baud_rate: 0

# Enable status LED
status_led:
    pin:
      number: GPIO2
      inverted: true
    
# Enable Home Assistant API
api:
  reboot_timeout: 1h

ota:
  password: "7f0a9c6493bf369b303410ce4915d3b4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rd6006 Fallback Hotspot"
    password: "BgDmzEZwl9tB"

captive_portal:

uart:
  id: mod_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
  data_bits: 8
  stop_bits: 1
  parity: none

modbus:
 id: modbus1

modbus_controller:
  - id: powersupply
    ## This address should be set to the value in the RD6006 config menu
    address: 0x01
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s

sensor:
  - platform: modbus_controller
    id: model
    name: "Model Number"
    entity_category: diagnostic
    modbus_controller_id: powersupply
    address: 0
    skip_updates: 10
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
  
  - platform: modbus_controller
    modbus_controller_id: powersupply
    address: 3
    id: firmware
    name: "Firmware version"
    entity_category: diagnostic
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  
  - platform: modbus_controller
    modbus_controller_id: powersupply
    address: 14
    id: input_voltage
    name: "Input voltage"
    device_class: voltage
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  
  - platform: modbus_controller
    id: temperature
    name: "Temperature"
    modbus_controller_id: powersupply
    device_class: temperature
    register_type: holding
    address: 4
    value_type: S_DWORD
    
  - platform: modbus_controller
    id: temperature_external
    name: "Temperature external"
    modbus_controller_id: powersupply
    register_type: holding
    address: 34
    value_type: S_DWORD
    device_class: temperature
    
  - platform: uptime
    name: "RD6006 Uptime"
  
  - platform: wifi_signal
    name: "RD6006 Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "RD6006 IP Address"
    ssid:
      name: "RD6006 Wi-Fi SSID"
    bssid:
      name: "RD6006 Wi-Fi BSSID"
  - platform: version
    name: "RD6006 Version"
    hide_timestamp: true

binary_sensor:
- platform: modbus_controller
  id: keypad_lock
  name: "Keypad lock"
  modbus_controller_id: powersupply
  entity_category: diagnostic
  device_class: lock
  register_type: holding
  address: 15
  bitmask: 0x1
  
number:
  - platform: modbus_controller
    id: backlight
    name: "Backlight"
    modbus_controller_id: powersupply
    entity_category: config
    address: 72
    icon: "mdi:lightbulb"
    value_type: U_WORD
    min_value: 0
    max_value: 5

  - platform: modbus_controller
    modbus_controller_id: powersupply
    id: output_voltage
    name: "Output voltage"
    address: 8
    entity_category: config
    icon: "mdi:sine-wave"
    value_type: U_WORD
    min_value: 0
    max_value: 60
    step: 0.01
    multiply: 100
  
  - platform: modbus_controller
    modbus_controller_id: powersupply
    id: output_current
    name: "Output current"
    address: 9
    entity_category: config
    icon: "mdi:current-dc"
    value_type: U_WORD
    min_value: 0
    max_value: 6
    step: 0.01
    multiply: 1000
    
switch:
  - platform: modbus_controller
    modbus_controller_id: powersupply
    id: output
    name: "Output"
    address: 18
    register_type: holding
    bitmask: 0x1
    entity_category: config